services:
  postgres:
    image: postgres:latest
    container_name: postgres-single
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data/order:/var/lib/postgresql/data
      - ./init/order/init.sql:/docker-entrypoint-initdb.d/init.sql


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-single
    ports:
      - "8989:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@admin.ca
      - PGADMIN_DEFAULT_PASSWORD=password

